### ISSUE TITLE
Create an SSH key and add it to GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-MaksMaidaanov#3]
> Note: it's best to complete this task from within the dev environment created in #2

See:
* https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#generating-a-new-ssh-key (you may omit adding a password)
* https://help.github.com/articles/connecting-to-github-with-ssh/

After completing instructions, post the result of the following command in a comment to this issue:
```shell
ssh -T git@github.com
```

Check yourself
--------------

If performed correctly, you'll see your GitHub username in the console output.

**Comment by MaksMaidaanov** [comment]
![image](https://user-images.githubusercontent.com/92547877/198585637-34ab4731-f801-4451-b6c5-557f86ff0da2.png)

**Comment by webknjaz** [comment]
It can't recognize you until you add the key to your account.

**Comment by webknjaz** [comment]
Note that you'll need to copy the private key to the system set up in #2 or repeat this task under that env.

**Comment by MaksMaidaanov** [comment]
![image](https://user-images.githubusercontent.com/92547877/200849049-a5caa3fd-7402-44c3-ab09-54119d6e5b62.png)

**Comment by webknjaz** [comment]
That screenshot says you never used the key to authenticate.
You still need to set up your Git client to use the key. On regular *NIX systems, when there's `~/.ssh/id_rsa`, it's picked up by SSH by default. Then, `ssh -T git@github.com` will mention your username, meaning that GitHub was able to authenticate you using the SSH key pair.

OTOH, if you use something weird like GUI / GitHub Desktop (which tends to resort to using an API token instead of an SSH key, AFAIK), you'll need to figure out how that works to make it use the private SSH key you generated corresponding to the public key added on GitHub.

But again, you'd need to redo all of this in the new env after you've done #2.

**Comment by MaksMaidaanov** [comment]
![Снимок экрана от 2022-11-16 23-32-35](https://user-images.githubusercontent.com/92547877/202309264-6e528659-10d1-4807-83a0-dd922db4365a.png)
![Снимок экрана от 2022-11-16 23-33-55](https://user-images.githubusercontent.com/92547877/202309290-29b2195c-4eb5-41cd-94c3-ed8414a50e3d.png)
![Снимок экрана от 2022-11-16 23-02-43](https://user-images.githubusercontent.com/92547877/202309223-a361ad79-e8ef-4afb-9231-790d73fb3c59.png)

**Comment by webknjaz** [comment]
I see it still hasn't been used. Try the `ssh` command to see if it works now. Also, I see you're using the `root` superuser. It is dangerous and is strongly recommended to use your own user instead so you don't corrupt your system by accident. Creating files under root will cause all sorts of file access problems because of insufficient privileges. `ssh` will also reject using an SSH key that is accessible by other users.
