### ISSUE TITLE
Create an empty commit on `main` (and push nothing else there!)

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-MaksMaidaanov#5]
```console
git commit --allow-empty -m 'Initial commit'
git push origin main
```

And report here after that.

P.S. It's best to do this task having read the first 3 chapters of the ProGit 2 book from #4.

**Comment by MaksMaidaanov** [comment]
![image](https://user-images.githubusercontent.com/92547877/198582170-1fbb7101-91ef-4af3-8d27-3f844e275309.png)
error: failed to push some refs to 'origin'

**Comment by webknjaz** [comment]
You won't be able to authenticate until you complete #3. It's visible from the screenshot posted there.

**Comment by webknjaz** [comment]
@MaksMaidaanov you needed to create an empty commit but instead you've added a new file. Fix this by force-pushing an empty commit in place of the incorrect one.

**Comment by MaksMaidaanov** [comment]
[maks@fedora django-girls-blog-MaksMaidaanov]$ git commit
[main 05702e2] Try one
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 django-girls-blog-MaksMaidaanov/main.py
[maks@fedora django-girls-blog-MaksMaidaanov]$ git push origin main

**Comment by webknjaz** [comment]
Looks like you still have an extra commit that adds a new file. It should be cleaned up before this can be considered resolved.

**Comment by webknjaz** [comment]
Alright, I've protected the branch now. So no more direct commits w/o PRs there.
